pipeline {
    agent any

    environment {
        IMAGE_NAME = "kirankapikad/flask-cicd-demo"
        IMAGE_TAG = "latest"
    }

    stages {

        stage("🔄 Clone Code") {
            steps {
                echo "📥 Cloning GitHub repository"
                git url: "https://github.com/Kiran-Kapikad/Git_MD/flask-cicd-demo.git", branch: "main"
            }
        }

        stage("🐳 Build Docker Image") {
            steps {
                echo "🔧 Building Docker image"
                sh "docker build -t $IMAGE_NAME:$IMAGE_TAG ./flask-cicd-demo/app"
            }
        }

        stage("📤 Push to Docker Hub") {
            steps {
                echo "🔐 Logging in and pushing image"
                withCredentials([usernamePassword(credentialsId: "dockerhub-creds", usernameVariable: "DOCKER_USER", passwordVariable: "DOCKER_PASS")]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage("🚀 Deploy to Kubernetes") {
            steps {
                echo "⛴ Deploying using kubectl"
                withKubeConfig(
                    credentialsId: 'kubeconfig',
                    serverUrl: '',
                    clusterName: '',
                    contextName: '',
                    namespace: '',
                    caCertificate: '',
                    restrictKubeConfigAccess: false
                ) {
                    sh '''
                        echo "📦 Applying deployment YAML"
                        kubectl apply -f ./flask-cicd-demo/k8s/deployment.yaml

                        echo "🌐 Applying service YAML"
                        kubectl apply -f ./flask-cicd-demo/k8s/service.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed! Check logs for details."
        }
    }
}

